### ISSUE TITLE
Packaged d3 overrides global/window d3

### ISSUE THREAD

**Issue by TheSharpieOne** [react-d3-library/react-d3-library#44]
The dist version comes with [it's own version of d3](https://github.com/react-d3-library/react-d3-library/blob/master/dist/react-d3-library.js#L4388-L13946). When importing react-d3-library this instance of d3 overrides any other version which may exist on the global/window.
This becomes an issue when `d3.event` is set in once instance and a handler in another instance see it as still being null.
It being prepackaged into the main file also would mean the final payload would have d3 in it twice making the file size larger.
I don't think this library should include it's own d3, it could look for it on the global/window scope or have the ability to receive d3 (something like:)

```
import d3 from 'd3';
import rd3 from 'react-d3-library';
const RD3Component = rd3.Component(d3);
```

forthermore, since it is prepackaged, external d3 is not even needed, just try [your example](http://codepen.io/danieljoonlee/pen/jrPoPE?editors=0010) without the d3 script (Pen Settings -> JavaScript -> Add External JavaScript -> remove d3 script from the list).

Right now, as a workaround, I am not including my own d3, which avoids the double the d3 lib in the bundled js. I grab d3 off the window when I need it.

```
// import d3 from 'd3';
import rd3 from 'react-d3-library';
// ... omitted for brevity
const d3 = window.d3; // explicitly get d3 from window.
```

**Comment by danieljoonlee** [comment]
I agree that that it might be overlapping, and that might create some issues, however I think it is a bit of a balancing act.  If you were to use Mike's newest version of D3 then a lot of this code won't be compatible, or vice versa for older versions.  Also, some users will be using specifically the template charts without wanting to use D3, and we create the template charts in D3.  I think in the future we can create modular parts like some other libraries do.  You made some really good points though, and I've written them down for future plans.  If you have any other ideas please do share.

**Comment by TheSharpieOne** [comment]
Heck, even exposing the version/instance of d3 included in react-d3-library would not be so bad. It would ensure people use a compatible version (aka, the one react-d3-library includes) and make it so one would not have to explicitly grab it from the window (which to me is my biggest complaint, feels dirty). 
```
import rd3 from 'react-d3-library';
const d3 = rd3.d3;
const RD3Component = rd3.Component;
```

**Comment by danieljoonlee** [comment]
That's a good idea.  We can make a note in the documentation that you can access D3 through the library.  I'll update the docs soon stating that.  Thanks dude :dancers:

**Comment by warrenronsiek** [comment]
+1 on making this work for D3v4.
